try:
	from setuptools import setup
except ImportError:
	from distutils.core import setup

config = {
	'description': 'Tool to parse the log generated by CXS and clear exploits without the risk of deleting system files.',
	'author': 'Sebastian',
	'url': 'None',
	'download_url': 'none yet',
	'author_email': 'seba.grillo@gmail.com',
	'version': '0.1',
	'install_requires': ['nose'],
	'packages': ['cxscleaner'],
	'scripts': ['bin/cxslogparser'],
	'name': 'cxscleaner'
}

setup(**config)

